version: '3.8'

services:
  app:
    container_name: cold-mail-backend
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      PORT: ${PORT}
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true
